spring:
  application:
    name: dubbo-provider
  main:
    allow-bean-definition-overriding: true
dubbo:
  scan:
    base-packages: cn.lcdiao.apache.dubbo.provider.service
  protocol:
    name: dubbo
    #-1:自动分配端口
    port: -1
  registry:
    address: nacos://134.175.116.100:8848